name: Style and build test

on:
  push:
    branches: [main]
    paths:
      - "*.py"
      - "**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "*.py"
      - "**/*.py"

jobs:
  ruff-lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.13.3"
          args: check .

  build-windows-exe:
    name: Build Windows .exe (PyInstaller)
    needs: ruff-lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build exe
        run: pyinstaller --onefile syno2bw.py
